### ISSUE TITLE
Use absolute imports instead of relative

### ISSUE THREAD

**Issue by hongshaoyang** [usdevs/cinnabot#14]
Fix relative imports that do not work. Assuming cloning cinnabot to `~/go/src/github.com/usdevs/cinnabot`, `basic.go` will complain:

```
cannot find package "cinnabot/model" in any of:
	/usr/local/go/src/cinnabot/model (from $GOROOT)
	/Users/shaoyang/go/src/cinnabot/model (from $GOPATH)go
```

**Solution**: Use absolute imports (`import "github.com/usdevs/cinnabot"` etc).

**Comment by SwampertX** [comment]
fixing this first, since it affects the installation in a new machine.
