### ISSUE TITLE
Fix travis builds

### ISSUE THREAD

**Issue by hongshaoyang** [usdevs/cinnabot#26]
Because a green badge looks good :D

**Comment by SwampertX** [comment]
There are 3 "guards" from the go family that are preventing us from getting a passing build, and I am going to list them in non-decreasing difficulty to fix:

`go fmt`: style issues. Quick fix: run `go fmt -w ./...` Long term: git hooks (insert issue here)

`go lint`: nice to have comments etc. Need to und the code and write relevant descriptions. Once-off and good coding habits

`go vet`: much harder to deal with, I believe it requires some minor refactoring.
