### ISSUE TITLE
Implement `/map`

### ISSUE THREAD

**Issue by hongshaoyang** [usdevs/cinnabot#33]
Implement `/map` (or `/lost`) 

- ```/map``` return a image of the NUS Campus (possibly [this one](http://map.nus.edu.sg/download/Kent-Ridge-Campus-Map.pdf))
- ```/map <faculty>``` or ```/map``` --> select faculty from button (KIV how exactly to select faculty): returns a map of that faculty
- Send link to [NUSMods venue finder](https://nusmods.com/venues)

KIV: how to select faculties
- Have buttons for faculties "SoC", "Science", etc.
- Possibly accept user input e.g. `"computing"`, `"utown"`

**Comment by seanlowcy77** [comment]
/map Function mostly done. Uploaded some png images of several maps of different parts of NUS - so that I can use the URL address in some part of the /map function (or rather NUSmap function in basic.go)

**Comment by seanlowcy77** [comment]
<img width="588" alt="Screenshot 2019-09-04 at 2 59 13 AM" src="https://user-images.githubusercontent.com/52877163/64200986-2a494b80-cec0-11e9-91ab-2f2ad271bd13.png">
